FROM 10.150.19.27:8123/centostest:1.03
RUN yum install -y \
  jdk \
  mariadb-server
ARG DB_USER=todouser
ARG DB_PASSWORD=password
ARG DB_NAME=todouser

RUN systemctl start mariadb && sleep 10 && \ 
  mysql -uroot -e "CREATE USER '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}'" && \ 
  mysql -uroot -e "GRANT ALL PRIVILEGES ON . TO '${DB_USER}'@'%' WITH GRANT OPTION" && \ 
  mysql -uroot -e "CREATE DATABASE ${DB_NAME}" && \ 
  mysqladmin -uroot shutdown

COPY  target/TodoDemo-0.0.1-SNAPSHOT.war .

EXPOSE 3306
EXPOSE 8080
CMD ["java","target/TodoDemo-0.0.1-SNAPSHOT.war" ]
